### ISSUE TITLE
Suggestion : Add a feature to replace sequences bigger in size than the original.

### ISSUE THREAD

**Issue by JimKatz** [BenjaminHalko/WiiMusicEditor#10]
I'm working on fixing some things for the Wii Music "RiiMajor" modpack. If this feature were implemented, it would solve all of our problems and allow us to greatly improve the modpack!

**Comment by BenjaminHalko** [comment]
As soon as I figure out how to I will definitely add it!

**Comment by BenjaminHalko** [comment]
I did it! Yay!
