### ISSUE TITLE
The editor glitched when updating.

### ISSUE THREAD

**Issue by FasterHumans** [BenjaminHalko/WiiMusicEditor#14]
Looks like a permissions error. Take a look at this screenshot.
![Screenshot_51](https://user-images.githubusercontent.com/83786923/119538467-c11f0100-bd50-11eb-8b69-2d65a44a1d04.png)

**Comment by BenjaminHalko** [comment]
Try redownloading the WiiMusicEditor from github. You can copy the settings.ini out of the folder then put it in the new folder to keep your settings.
