### ISSUE TITLE
No such file or directory: '.../.../Disk/DATA/files/Sound/MusicStatic/rp_Music_sound.brsar'

### ISSUE THREAD

**Issue by TheGoldenPotion** [BenjaminHalko/WiiMusicEditor#25]
I'm using a US rom for Wii Music and every time I open the batch file and place the directory where the rom is in, I get this error:

`FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/[nope]/[also nope]/WiiMusicEditor-main/Disk/DATA/files/Sound/MusicStatic/rp_Music_sound.brsar'`

I looked at where the .brsar file is and it turns out it's in the correct directory, except the folder "DATA" doesn't exist. The directory is:
`WiiMusicEditor-main/Disk/files/Sound/MusicStatic/rp_Music_soung.brsar`

**Comment by FasterHumans** [comment]
Sounds like your Wii Music ROM is corrupted. Try re-dumping.
