### ISSUE TITLE
Faulty Features (read below)

### ISSUE THREAD

**Issue by AlphaMan2503** [BenjaminHalko/WiiMusicEditor#26]
1. Replacing a song with a MIDI file larger than the original results in malfunctioning of the song midway through playback.
Maybe re-implementing the size of each song in the Python Patcher can resolve this temporarily.
(See Swap Meet.mid in MIDI.ZIP below)

2. Song Length in game seems unaffected despite altering values during patching. This results in long silent periods after the notes have ended.
(See Song of Storms.mid in MIDI.ZIP below)

3. Time Signature (3/4) / (4/4) are mismatched with the percussion if the original song had a different Time Signature. Example: Patching a 3/4 song into a 4/4 song will result in 4/4 percussion remaining and playing out of sync with the rest of the song.

4. Some songs begin before the Melody Countdown appears on screen. I believe this is due to some songs having the Tutes play before the song begins and will need to be handled on a case by case basis.

----------------------------------------------------------------------------------------------------------------------------------------------
Testing Environment:
Windows 10 64-bit Home
Dolphin 5.0-14344
Wii Console [RVL-001] using Homebrew Channel & USB Loader GX
WiiMusicEditor.py - Main and Beta releases
MIDI Files Used: 
[MIDI.zip](https://github.com/BenjaminHalko/WiiMusicEditor/files/6911690/MIDI.zip)
----------------------------------------------------------------------------------------------------------------------------------------------

PS. I am fluent in C. If you would like some help on this project that requires the use of C, I am more than willing to assist.

**Comment by FasterHumans** [comment]
With the example of 2 and 3, your issues are unrelated to the editor yourself. Some songs also behave weirdly in general. Your Swap Meet MIDI also has 5 tracks, not 4. **Please make sure your problem is related to the Editor itself, not MIDIs or the Game. **
