### ISSUE TITLE
Not working properly on a European ISO

### ISSUE THREAD

**Issue by TheGoldenPotion** [BenjaminHalko/WiiMusicEditor#30]
Basically, I tried to put a custom song replaced over Twinkle Twinkle Little Star using a .mid file, but when I opened Dolphin, this happened:

[[Video](https://drive.google.com/file/d/1TOOm7COvoOb5e_8sr7oUPXIo7-QEhRBV/view?usp=sharing)]

Why does this happen?

**Comment by BenjaminHalko** [comment]
Ok so this seems to be what is happening. The editor is guessing the tempo of the song wrong. When it says "Found some info for the auto fill" thing check the tempo if it matches the tempo of the actual song. If it doesn't say no to the autofill and enter it in manually

**Comment by TheGoldenPotion** [comment]
I tried doing this but the end result was just the same.

**Comment by BenjaminHalko** [comment]
Did you try enabling cheats in Dolphin?

**Comment by BenjaminHalko** [comment]
If you want to send me your .midi file I can try seeing what the problem is

**Comment by TheGoldenPotion** [comment]
Ok
Im also adding the Musescore file in case I did something wrong when exporting the midi.
[The Midi file and mscz File](https://github.com/BenjaminHalko/WiiMusicEditor/files/7186940/the_thing.zip)

**Comment by TheGoldenPotion** [comment]
Have you found the error yet?

**Comment by liam2503** [comment]
Did you use a MIDI exported directly from MuseScore? You should save it again through another MIDI Editor like https://www.midieditor.org/

**Comment by azabiphetamine** [comment]
I did use that very midi editor to export it again and I got the error.

**Comment by liam2503** [comment]
Oh, I think I see your problem. While your notes are separated onto different tracks, I think having them all on the same MIDI channel is causing some errors. Try separating each part (Melody, Harmony, etc.) into its own instrument in MuseScore. That should automatically separate the instruments into different tracks and channels. Then all you need to do is press Save once you open the MIDI File in MidiEditor.

**Comment by BenjaminHalko** [comment]
Sorry for taking so long to responded (I have been working on the new version of the editor). I can confirm that giving each track their own channel fixes the problem. Here is the fixed midi: [bonetrousle.zip](https://github.com/BenjaminHalko/WiiMusicEditor/files/7740129/bonetrousle.zip)

**Comment by BenjaminHalko** [comment]
Sorry for taking so long to respond, I believe this happened because I messed up the region differences. I think I might have fixed this in the new version of the editor: https://github.com/BenjaminHalko/WiiMusicEditorPlus/releases/latest I did a quick test using the exact midi you have sent and it seems to have work. Again, sorry for taking so long.
